[package]
name = "fuzzy_log"
version = "0.1.0"
authors = ["J <joshua.lockerman@yale.edu>"]

[dependencies]
bitflags = "0.4"
custom_derive = "0.1"
grabbag_macros = "0.1"
newtype_derive = "0.1"
uuid = "0.1"
log = "0.3"
rand = "0.3"
rustc-serialize = "0.3"
time = "0.1"
mio = "0.5"
nix = "*"
net2 = "0.2"



[dev-dependencies]
env_logger = "0.3"
