[package]
name = "fuzzy_log"
version = "0.1.0"
authors = ["J <joshua.lockerman@yale.edu>"]

[dependencies]
bitflags = "0.3"
custom_derive = "0.1.2"
grabbag_macros = "0.1.0"
newtype_derive = "0.1.2"
uuid = "0.1.17"
