[package]
name = "fuzzy_log"
version = "0.1.0"
authors = ["J <joshua.lockerman@yale.edu>"]

[dependencies]
bitflags = "0.3"
custom_derive = "0.1.2"
grabbag_macros = "0.1.0"
mio = "0.4"
newtype_derive = "0.1.2"
uuid = "0.1.17"
log = "^0.3.2"
pnet = "*"
rustc-serialize = "0.3"
time = "0.1"


[dev-dependencies]
env_logger = "0.3"

