[package]
name = "zk_test"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
crossbeam = "0.2.10"
rand = "0.4"
structopt = "0.0.5"
structopt-derive = "0.0.5"
zipf = "1.1.0"
zookeeper = {path = ".."}

[features]
print_stats = ["zookeeper/print_stats"]
