[package]
name = "packet-macro-impl"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
syn = "0.11.9"
synom = "0.11.3"
quote = "0.3.15"

[lib]
proc-macro = true

[features]
default = ["syn/full"]
