[package]
name = "java_proxy"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
env_logger = "0.3"
mio = "0.6.6"
byteorder = "1.1.0"
fuzzy_log_client = {path = "../../fuzzy_log_client"}
structopt = "0.0.5"
structopt-derive = "0.0.5"
