[package]
name = "tokio_server"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
futures = "0.1"
fuzzy_log_packets = {path = "../fuzzy_log_packets"}
fuzzy_log_util = {path = "../fuzzy_log_util"}
fuzzy_log_server = {path = "../fuzzy_log_server"}
