[package]
name = "fuzzy_log_client"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
fuzzy_log_packets = {path = "../fuzzy_log_packets"}
fuzzy_log_util = {path = "../fuzzy_log_util"}
log = "0.3"
mio = "0.6.6"
reactor = {path = "../reactor"}

[features]
print_stats = []
