[package]
name = "counter"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
crossbeam = "0.2.10"
env_logger = "0.3"
fuzzy_log_client = {path = "../../fuzzy_log_client"}
log = "0.3"
mio = "0.6.6"
rand = "0.3"
structopt = "0.0.5"
structopt-derive = "0.0.5"
