[package]
name = "view_builder"
version = "0.1.0"
authors = ["Joshua Lockerman <>"]

[dependencies]
bincode = "0.8.0"
fuzzy_log_client = {path = "../../fuzzy_log_client"}
serde = "1"

[dev-dependencies]
fuzzy_log_server = {path = "../../fuzzy_log_server"}
matches = "0.1.6"
serde_derive = "1"
